stages:
  - build
  - lint

cache:
  paths:
    - vendor

composer:
  stage: build
  image: composer:2.4
  script:
    - composer install --ignore-platform-reqs

'php-cs-fixer':
  stage: lint
  extends: composer
  script: |
    vendor/bin/php-cs-fixer check -v --format=junit --diff --using-cache=no > logs/php-cs-fixer-junit.xml
  artifacts:
    when: always
    paths:
      - logs/php-cs-fixer-junit.xml
    reports:
      junit: logs/php-cs-fixer-junit.xml
