name: linting

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  php-cs-fixer:
    name: "🧹 PHP-CS-Fixer"
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "🗄️ cache"
        uses: actions/cache@v4
        with:
          path: .php-cs-fixer.cache
          key: ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-${{ github.repository }}-phpcsfixer-

      - name: "🧹 run PHP-CS-Fixer"
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.dist.php

      - name: "🤖 commit fixed code"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'fix: Apply PHP-CS-FIXER changes'
